# Generated by Django 3.1 on 2020-08-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
